plugin: aws_ec2
regions:
  - eu-west-3
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
host_key_checking: false
hostnames:
  - network-interface.addresses.association.public-ip  # Use the correct field for public IP
