plugin: aws_ec2
regions:
  - eu-west-3
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
host_key_checking: false
#hostnames:
 # - network-interface.addresses[0].association.public-ip  # Adjusted for list index
