---
- name: Install and configure Elasticsearch
  hosts: aws_ec2  
  remote_user: jenkins
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: roles/my_elasticsearch_role
      elasticsearch_group: "elasticsearch"
      elasticsearch: "elasticsearch"
